/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fixtesttrade;

/**
 *
 * @author USER
 */
public class FIXTestTrade extends javax.swing.JFrame {

    /**
     * Creates new form FIXTestTrade
     */
    public FIXTestTrade() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cmdSend = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtStop = new javax.swing.JTextField();
        txtLimit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cboType = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cboSide = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtSymbol = new javax.swing.JTextField();
        txtOrderID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtQuatity = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtOrderCancelServerOrderID = new javax.swing.JTextField();
        cmdCancel = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtOrderReplaceServerOrderID = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtOrderReplaceQuatity = new javax.swing.JTextField();
        txtOrderReplaceLimit = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtOrderReplaceStop = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cmdReplace = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Test Trade");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Order Entry", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdSend.setText("Send");
        jPanel1.add(cmdSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 80, -1));

        jLabel7.setText("Stop");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        txtStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStopActionPerformed(evt);
            }
        });
        jPanel1.add(txtStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 100, -1));
        jPanel1.add(txtLimit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 100, -1));

        jLabel6.setText("Limit");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jLabel5.setText("Type");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        cboType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MARKET", "LIMT", "STOP", "STOP LIMIT" }));
        jPanel1.add(cboType, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 100, -1));

        jLabel4.setText("Side");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        cboSide.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BUY", "SELL" }));
        jPanel1.add(cboSide, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 100, -1));

        jLabel3.setText("Symbol");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        txtSymbol.setText("EUR/USD");
        txtSymbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSymbolActionPerformed(evt);
            }
        });
        jPanel1.add(txtSymbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 100, -1));
        jPanel1.add(txtOrderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 100, -1));

        jLabel2.setText("Order ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel8.setText("Quatity");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        txtQuatity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuatityActionPerformed(evt);
            }
        });
        jPanel1.add(txtQuatity, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 33, 190, 310));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Order Cancel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Order ID fro server");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        txtOrderCancelServerOrderID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderCancelServerOrderIDActionPerformed(evt);
            }
        });
        jPanel2.add(txtOrderCancelServerOrderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 93, -1));

        cmdCancel.setText("Cancel");
        jPanel2.add(cmdCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 90, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 220, 100));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Order Replace", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Order ID fro server");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        txtOrderReplaceServerOrderID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderReplaceServerOrderIDActionPerformed(evt);
            }
        });
        jPanel3.add(txtOrderReplaceServerOrderID, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 93, -1));

        jLabel11.setText("Quatity");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 40, -1));
        jPanel3.add(txtOrderReplaceQuatity, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 93, -1));
        jPanel3.add(txtOrderReplaceLimit, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 93, -1));

        jLabel12.setText("Limit");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 30, -1));
        jPanel3.add(txtOrderReplaceStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 93, -1));

        jLabel13.setText("Stop");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 30, -1));

        cmdReplace.setText("Replace");
        cmdReplace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdReplaceActionPerformed(evt);
            }
        });
        jPanel3.add(cmdReplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 93, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 220, 200));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtOrderReplaceServerOrderIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderReplaceServerOrderIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderReplaceServerOrderIDActionPerformed

    private void txtOrderCancelServerOrderIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderCancelServerOrderIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOrderCancelServerOrderIDActionPerformed

    private void cmdReplaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdReplaceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmdReplaceActionPerformed

    private void txtSymbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSymbolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSymbolActionPerformed

    private void txtStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStopActionPerformed

    private void txtQuatityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuatityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuatityActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FIXTestTrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FIXTestTrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FIXTestTrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FIXTestTrade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FIXTestTrade().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboSide;
    private javax.swing.JComboBox<String> cboType;
    private javax.swing.JButton cmdCancel;
    private javax.swing.JButton cmdReplace;
    private javax.swing.JButton cmdSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtLimit;
    private javax.swing.JTextField txtOrderCancelServerOrderID;
    private javax.swing.JTextField txtOrderID;
    private javax.swing.JTextField txtOrderReplaceLimit;
    private javax.swing.JTextField txtOrderReplaceQuatity;
    private javax.swing.JTextField txtOrderReplaceServerOrderID;
    private javax.swing.JTextField txtOrderReplaceStop;
    private javax.swing.JTextField txtQuatity;
    private javax.swing.JTextField txtStop;
    private javax.swing.JTextField txtSymbol;
    // End of variables declaration//GEN-END:variables
}
